Add: Regex to exclude certain commits from the changelog
FabricMC/fabric-action-scripts pull request #3
Opened 2021-07-24 14:11 UTC by spnda

As many people sometimes have commits that do not affect the users, a regex to filter the output might be helpful. For example `(Codechange|Refactor)(.*)` would be a helpful regex in my repositories, as those commits should really not be noted inside of the changelog. (I know, this might not be specific to any fabric project - but it still could be useful for other developers.)

2021-07-24 14:47 UTC, modmuss50 requested changes
Im not too sure this works.

I really need to write some unit tests for this to make it easier to develop.

2021-07-24 14:47 UTC, modmuss50 commented on src/changelog.ts
> +  let log = gitLog(previousCommit, releaseCommit);
dont you need to `await gitLog` here?

2021-07-24 14:47 UTC, modmuss50 commented on src/changelog.ts
> +    return commit_regex
Shouldnt this be `log` not `commit_regex`

2021-07-24 14:52 UTC, modmuss50 commented on src/changelog.ts
> +  if (commit_regex != "") {
`if (commit_regex) {`

Should be fine here.

2021-07-24 15:19 UTC, spnda commented
> Im not too sure this works.
> 
> I really need to write some unit tests for this to make it easier to develop.

I just wrote a small script to test this implementation, see [here](https://gist.github.com/spnda/8020225c33b5d21b56faa0477dbae66d). It seems to work just fine.

2021-07-24 15:41 UTC, modmuss50 approved these changes

2022-02-28 11:20 UTC, spnda commented
@modmuss50 Any update on this?

2022-02-28 11:22 UTC, modmuss50 commented
Tottaly forgot about this, you should have reminded me sooner :) Still looks good, thanks.

2022-02-28 11:22 UTC, merged